language: python

cache:
  - ccache
  - pip

sudo: true

env:
    TOX_ENV=py34,py35

install:
  - pip install -r requirements-development.txt

script:
  - make clean
  - make quality
  - tox -e $TOX_ENV

notifications:
    email:
        - travis@joaojunior.org
